--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/okt/Pics/kristaps-ungurs-B6CN3tgm6c4-unsplash.jpg"

-- Special
background="#141211"
foreground="#e8d0a2"
cursor="#e8d0a2"

-- Colors
color0="#141211"
color1="#98341A"
color2="#9F5B1B"
color3="#BA5234"
color4="#DC6414"
color5="#EB9622"
color6="#F3AD52"
color7="#e8d0a2"
color8="#a29171"
color9="#98341A"
color10="#9F5B1B"
color11="#BA5234"
color12="#DC6414"
color13="#EB9622"
color14="#F3AD52"
color15="#e8d0a2"
