foreground   #e8d0a2
background   #141211
cursor       #e8d0a2

color0       #141211
color8       #a29171
color1       #98341A
color9       #98341A
color2       #9F5B1B
color10      #9F5B1B
color3       #BA5234
color11      #BA5234
color4       #DC6414
color12      #DC6414
color5       #EB9622
color13      #EB9622
color6       #F3AD52
color14      #F3AD52
color7       #e8d0a2
color15      #e8d0a2
