# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$jobs\
${custom.tmux}\
$character\
"""

right_format = """
$status\
$cmd_duration\
$directory\
$git_branch\
$git_state\
$git_status\
${custom.jj}\
${custom.jjstate}\
$hostname\
"""

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[%](bold)"
error_symbol = "[%](bold red)"
format = "$symbol "

[custom.tmux]
when = "test $TMUX != ''"
format = "t "
style = "bold green"

[jobs]
format = '[\[$number\]]($style) '
number_threshold = 1

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[directory]
truncate_to_repo	= false
truncation_length = 4
truncation_symbol = '…/'
read_only = ''
style = "none"

[git_branch]
format = "[$branch]($style)"
style = "green"

[git_status]
conflicted = "*"
untracked = "n"
modified = "+"
staged = "s"
renamed = "r"
deleted = "x"
stashed = "≡"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](6) ($ahead_behind$stashed)]($style)"
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[hostname]
ssh_symbol = '˝'
format = '[$hostname$ssh_symbol]($style)'
style = "yellow"

[custom.jj]
command = '''
jj log -r@ -n1 --ignore-working-copy --no-graph --color always  -T '
  separate(" ",
    bookmarks.map(|x| if(
        x.name().substr(0, 10).starts_with(x.name()),
        x.name().substr(0, 10),
        x.name().substr(0, 9) ++ "…")
      ).join(" "),
    tags.map(|x| if(
        x.name().substr(0, 10).starts_with(x.name()),
        x.name().substr(0, 10),
        x.name().substr(0, 9) ++ "…")
      ).join(" "),
    surround("\"","\"",
      if(
         description.first_line().substr(0, 24).starts_with(description.first_line()),
         description.first_line().substr(0, 24),
         description.first_line().substr(0, 23) ++ "…"
      )
    ),
    if(conflict, "conflict"),
    if(divergent, "divergent"),
    if(hidden, "hidden"),
  )
'
'''
when = "jj root"
symbol = "jj"

[custom.jjstate]
when = "jj root"
command = '''
jj log -r@ -n1 --no-graph -T "" --stat | tail -n1 | sd "(\d+) files? changed, (\d+) insertions?\(\+\), (\d+) deletions?\(-\)" ' ${1}m ${2}+ ${3}-' | sd " 0." ""
'''
